# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-13 15:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_post_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='overview',
            new_name='author',
        ),
    ]
