# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-22 04:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20160315_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user_name',
            field=models.CharField(blank=True, default='Ananomous', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='user_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='home'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
