# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-22 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20160322_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user_name',
            field=models.CharField(blank=True, default='Ananomous', max_length=200),
        ),
    ]
