# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-22 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20160322_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured',
            field=models.NullBooleanField(default='False'),
        ),
    ]
