# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-23 07:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20160322_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='img',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user_text',
        ),
    ]
