# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-23 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_post_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured',
            field=models.BooleanField(default='False'),
        ),
    ]
