# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-23 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20160323_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(choices=[('#POVERTY', '#POVERTY'), ('#EDUCATION', '#EDUCATION'), ('#ABUSE', '#ABUSE'), ('#ILLETERACY', '#ILLETERACY'), ('#CRIME', '#CRIME'), ('#DRUG ABUSE', '#DRUG ABUSE'), ('#CHILD LABOUR', '#CHILD LABOUR'), ('#CASTEISM', '#CASTEISM'), ('#CORUPTION', '#CORUPTION')], default='#', max_length=20),
        ),
    ]
