# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-23 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_post_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='taggie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_grp', models.CharField(choices=[('#POVERTY', '#POVERTY'), ('#EDUCATION', '#EDUCATION'), ('#ABUSE', '#ABUSE'), ('#ILLETERACY', '#ILLETERACY'), ('#CRIME', '#CRIME'), ('#DRUG ABUSE', '#DRUG ABUSE'), ('#CHILD LABOUR', '#CHILD LABOUR'), ('#CASTEISM', '#CASTEISM'), ('#CORUPTION', '#CORUPTION')], default='#', max_length=40)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(to='home.taggie'),
        ),
    ]
